#' An abundance table in long format. 
#'
#' A dataset containing the number of reads from unique ASVs from different samples
#'
#' @format A data frame with 1025 rows and 4 variables:
#' \describe{
#'   \item{Sample_name}{a character vector, the last digit includes the PCR replicate}
#'   \item{Locus}{which locus where the sequences from, numeric}
#'   \item{Hash}{The sequence found, Hashed using sha1 for ease of storage and consistency }
#'   \item{nReads}{The number of times that hash was found in that sample}
#'   ...
#' }
#' @source {Generated by the Author}