# A function that takes a DNAseq and generates mutations
# The goal is to get a set of sequences to check the ability of
# classifying algorithms to detect variants either generated by PCR
# or naturally occuring variants that had not been sequenced yet

# When we downloaded the genbak data, we used the ape format (from insect)
# The function should allow for either that format or the 
# character string from seqinr




mutation <- function(sequence = NULL, format = "bin", n.mutations = NA, prob.mutation = NA){
  
  require(tidyverse)
  require(insect)
  
  lapply(sequence[1], unique)[[1]] -> options.for.mutations
  
 
  if (is.na(n.mutations) & is.na(prob.mutation)| !is.na(n.mutations) & !is.na(prob.mutation)){
    return(print("Error: please enter one and only one of these: a number of mutations, or the probability of mutation"))
  }
  
  
  if (format == "bin"){
    
    lapply(sequence, length) -> l.input
   
    # in case we want a fixed number of mutations
    
    if (!is.na(n.mutations)){
      
     # select the spots to be mutated
      
    spots <- map(l.input, ~ sample(1:.x, n.mutations, replace = F))
      
    
     # replace the value
      
    output <- map2(sequence, spots, function(.x,.y) {
        .x[.y] <- map_raw(.x[.y],  function(.z) {
        options.for.mutations [!options.for.mutations %in% .z] %>% 
          sample(1)
      } ) 
        
   
    return(.x)
      })
   class(output) <- "DNAbin"
      return(output)
      
     }
    
  }
}
